
name: uct_chat
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  
  firebase_core: ^2.24.2

  firebase_auth: ^4.16.0

  google_sign_in: ^6.1.6

  cloud_firestore: ^4.1.0

  cached_network_image: ^3.3.1

  image_picker: ^1.0.7

  firebase_storage: ^11.6.0

  emoji_picker_flutter: ^1.6.3

  firebase_messaging: ^14.7.10

  http: ^0.13.3

  flutter_notification_channel: ^2.0.0

  gallery_saver: ^2.3.2

  flutter_bloc: ^8.1.3
  
  flutter_sound: ^9.2.13

  permission_handler: ^11.0.1

  audioplayers: ^5.2.1

  zego_uikit_prebuilt_call: ^3.17.10
  
  zego_uikit_signaling_plugin: ^2.7.0

  floating_action_bubble: ^1.1.4
  awesome_dialog: ^3.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1

flutter:

  uses-material-design: true

  assets:
    - images/