// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAIw3fAbXxn7RoKdHmTLU9n3uywGDzIBjE',
    appId: '1:200684019448:web:372586f4571704335b650d',
    messagingSenderId: '200684019448',
    projectId: 'chat-app-a178b',
    authDomain: 'chat-app-a178b.firebaseapp.com',
    storageBucket: 'chat-app-a178b.appspot.com',
    measurementId: 'G-4HL82ZQ9QK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoiNd8An7Z_-xnVoLjyTN-P-3eZ25rWrw',
    appId: '1:200684019448:android:96dc016c2bbecf755b650d',
    messagingSenderId: '200684019448',
    projectId: 'chat-app-a178b',
    storageBucket: 'chat-app-a178b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAM3sWxn-NLZ25YKA0FV7orSmcGz5-4tng',
    appId: '1:200684019448:ios:b5f44d1f74ad0ce65b650d',
    messagingSenderId: '200684019448',
    projectId: 'chat-app-a178b',
    storageBucket: 'chat-app-a178b.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAM3sWxn-NLZ25YKA0FV7orSmcGz5-4tng',
    appId: '1:200684019448:ios:ae638249195d2cba5b650d',
    messagingSenderId: '200684019448',
    projectId: 'chat-app-a178b',
    storageBucket: 'chat-app-a178b.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
